### ISSUE TITLE
False Positive - Deprecated __toString call - getcwd()

### ISSUE THREAD

**Issue by laurin1** [funivan/PhpClean#147] opened 2021-08-21 15:04 UTC
Actually, this affects several native PHP functions, but the only example I can find at this moment is this one:

![image](https://user-images.githubusercontent.com/75857/130325999-c0ff7590-485e-4b3e-b341-65c5dbb21f34.png)

Maybe I am misunderstanding, but what in PHP has been deprecated to make this an issue? The return value for getcwd() is string|false. Are you saying that false concatenated will no longer be evaluated as an empty string? If that is the case, can you point me to that in the PHP docs or release notes? Otherwise, this is a false positive.

**Comment by orklah** [comment] 2021-08-24 07:37
Duplicate of #143

**Comment by funivan** [comment] 2021-09-09 06:19
Thanks for the report. I will fix it 👀

**Comment by funivan** [comment] 2021-10-04 09:22
Fixed: https://plugins.jetbrains.com/plugin/11272-phpclean/versions/stable/138437

**Closed by funivan** 2021-10-04 09:22 UTC
